"""adding the blog section

Revision ID: 00b0bd192ab6
Revises: 291fa7838cbb
Create Date: 2024-06-26 18:05:32.483922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b0bd192ab6'
down_revision = '291fa7838cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('alt', sa.String(), nullable=False),
    sa.Column('title_tag', sa.String(), nullable=False),
    sa.Column('url_link', sa.String(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
