"""making additional changes

Revision ID: 291fa7838cbb
Revises: 863ac0da8dfb
Create Date: 2024-06-06 11:50:39.163446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291fa7838cbb'
down_revision = '863ac0da8dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_title_registered', sa.String(), nullable=False),
    sa.Column('course_description_registered', sa.Text(), nullable=False),
    sa.Column('course_duration_registered', sa.String(), nullable=False),
    sa.Column('course_lesson_registered', sa.String(), nullable=False),
    sa.Column('course_lesson_registered_status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_registers')
    # ### end Alembic commands ###
