"""removed unnecessary contents

Revision ID: 863ac0da8dfb
Revises: a2759710cf62
Create Date: 2024-06-04 12:50:36.000095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863ac0da8dfb'
down_revision = 'a2759710cf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('plan')
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
